spring.application.name=beout_backend
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/beout
spring.datasource.username=postgres
spring.datasource.password=Jin800##
spring.jpa.hibernate.ddl-auto = update
